### ISSUE TITLE
Project Checklist: Menu Slider and Modal

### ISSUE THREAD

**Issue by RobsonVinicius** [RobsonVinicius/menu-slider.modal#1]
## Menu Slider & Modal DOM & CSS

- [x]  Project HTML
- [x]  Navbar Styling
- [x]  Header & Modal Styling
- [x]  Menu & Modal Toogle
- [x] Deploy and Generating Link to live
